package constants

// Code generated by go generate; DO NOT EDIT.

const (
	IDTYPE_BARCLAYS_TICKER                = "BARCLAYS_TICKER"
	IDTYPE_BASE_TICKER                    = "BASE_TICKER"
	IDTYPE_COMPOSITE_ID_BB_GLOBAL         = "COMPOSITE_ID_BB_GLOBAL"
	IDTYPE_ID_BB                          = "ID_BB"
	IDTYPE_ID_BB_8_CHR                    = "ID_BB_8_CHR"
	IDTYPE_ID_BB_GLOBAL                   = "ID_BB_GLOBAL"
	IDTYPE_ID_BB_GLOBAL_SHARE_CLASS_LEVEL = "ID_BB_GLOBAL_SHARE_CLASS_LEVEL"
	IDTYPE_ID_BB_SEC_NUM_DES              = "ID_BB_SEC_NUM_DES"
	IDTYPE_ID_BB_UNIQUE                   = "ID_BB_UNIQUE"
	IDTYPE_ID_CINS                        = "ID_CINS"
	IDTYPE_ID_COMMON                      = "ID_COMMON"
	IDTYPE_ID_CUSIP                       = "ID_CUSIP"
	IDTYPE_ID_CUSIP_8_CHR                 = "ID_CUSIP_8_CHR"
	IDTYPE_ID_EXCH_SYMBOL                 = "ID_EXCH_SYMBOL"
	IDTYPE_ID_FULL_EXCHANGE_SYMBOL        = "ID_FULL_EXCHANGE_SYMBOL"
	IDTYPE_ID_ISIN                        = "ID_ISIN"
	IDTYPE_ID_ITALY                       = "ID_ITALY"
	IDTYPE_ID_SEDOL                       = "ID_SEDOL"
	IDTYPE_ID_SHORT_CODE                  = "ID_SHORT_CODE"
	IDTYPE_ID_TRACE                       = "ID_TRACE"
	IDTYPE_ID_WERTPAPIER                  = "ID_WERTPAPIER"
	IDTYPE_OCC_SYMBOL                     = "OCC_SYMBOL"
	IDTYPE_OPRA_SYMBOL                    = "OPRA_SYMBOL"
	IDTYPE_TICKER                         = "TICKER"
	IDTYPE_TRADEBOOK_TICKER               = "TRADEBOOK_TICKER"
	IDTYPE_TRADING_SYSTEM_IDENTIFIER      = "TRADING_SYSTEM_IDENTIFIER"
	IDTYPE_UNIQUE_ID_FUT_OPT              = "UNIQUE_ID_FUT_OPT"
	IDTYPE_VENDOR_INDEX_CODE              = "VENDOR_INDEX_CODE"
)
