// Code generated by go generate; DO NOT EDIT.
package constants

const (
	MARKETSECDES_Comdty = "Comdty"
	MARKETSECDES_Corp   = "Corp"
	MARKETSECDES_Curncy = "Curncy"
	MARKETSECDES_Equity = "Equity"
	MARKETSECDES_Govt   = "Govt"
	MARKETSECDES_Index  = "Index"
	MARKETSECDES_MMkt   = "M-Mkt"
	MARKETSECDES_Mtge   = "Mtge"
	MARKETSECDES_Muni   = "Muni"
	MARKETSECDES_Pfd    = "Pfd"
)
